version: '3.9'

services:
  backend:
    build:
      context: ./app
      dockerfile: ../Dockerfile  
    container_name: rag_fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/data:/app/data
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile      
    container_name: rag_client
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
